"""The reference numbers in paper/main.tex must match analysis/summary_table.csv.

CLAUDE.md rule 4 says no number is typed into the paper by hand.

* ``tab:fullmetrics``, ``tab:dirichlet`` and ``tab:lowdata`` \\input a tabular
  generated by ``scripts/export_latex_tables.py`` (reference rows from the analysis,
  federated rows ``\\PHs`` placeholders).  This test checks that main.tex inputs
  them inside the right table, and re-derives every reference cell of the
  generated files -- balanced accuracy pooled (primary) and client mean
  (secondary), mean and 95 % CI -- from ``analysis/summary_table.csv``.
* ``tab:protocol_effect`` still carries its group-level accuracy cells inline and
  is pinned here cell by cell.
* The superseded final-epoch reference cells of tab:dirichlet / tab:lowdata and
  the old communication volume must not reappear.
"""

import os
import re

import pandas as pd
import pytest

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MAIN_TEX = os.path.join(ROOT, "paper", "main.tex")
SUMMARY = os.path.join(ROOT, "analysis", "summary_table.csv")

pytestmark = pytest.mark.skipif(
    not (os.path.isfile(MAIN_TEX) and os.path.isfile(SUMMARY)),
    reason="paper/main.tex and analysis/summary_table.csv are both needed")

# the mean +- std columns of the generated tab:fullmetrics after its two balanced-
# accuracy columns (pooled primary and client mean, both mean [CI]), in order; the
# first entry stands for those two and is checked separately.  Percentages except MCC.
FULLMETRICS_COLUMNS = [
    ("selected_test_balanced_accuracy", 100.0),
    ("selected_test_mcc", 1.0),
    ("selected_test_accuracy", 100.0),
    ("selected_test_recall", 100.0),
    ("selected_test_specificity", 100.0),
    ("selected_test_macro_f1", 100.0),
    ("selected_test_roc_auc", 100.0),
]


def _summary():
    df = pd.read_csv(SUMMARY)
    return df[df.protocol == "group"]


def _cells(line):
    """The ``$a \\pm b$`` pairs of one LaTeX table row, in order."""
    return [(float(a), float(b)) for a, b in
            re.findall(r"\$([0-9.]+) \\pm ([0-9.]+)\$", line)]


def _row(tex, table_label, method, distribution_block):
    """Find one ``& <method> &`` row inside the named table environment."""
    start = tex.index(r"\label{%s}" % table_label)
    end = tex.index(r"\end{table", start)
    block = tex[start:end]
    # the non-IID rows come after the \midrule that follows the IID ones
    halves = block.split(r"\multirow")
    half = halves[1] if distribution_block == "iid" else halves[2]
    for line in half.splitlines():
        # the method cell may carry a scarce-minority marker, e.g. "Local-only$^{\dagger}$"
        if re.search(r"&\s*%s\s*(\$\^\{\\dagger\}\$)?\s*&" % re.escape(method), line):
            return line
    raise AssertionError("no %r row in %s (%s)" % (method, table_label, distribution_block))


def _lookup(summary, distribution, kind, metric):
    sel = summary[(summary.distribution == distribution) & (summary.kind == kind)
                  & (summary.metric == metric)]
    assert len(sel) == 1, "expected one %s/%s/%s row, got %d" % (
        distribution, kind, metric, len(sel))
    return float(sel.iloc[0]["mean"]), float(sel.iloc[0]["std"])


TABLES = os.path.join(ROOT, "paper", "tables")
GENERATED = {"tab:fullmetrics": "fullmetrics_tabular.tex",
             "tab:dirichlet": "dirichlet_tabular.tex",
             "tab:lowdata": "lowdata_tabular.tex"}
PRIMARY_BA = "selected_test_balanced_accuracy"
SECONDARY_BA = "selected_test_clientmean_balanced_accuracy"


def _generated(name):
    return open(os.path.join(TABLES, name), encoding="utf-8").read()


def _ci_cells(line):
    """``m [lo, hi]`` cells of one generated row, in order."""
    return [tuple(float(x) for x in t) for t in
            re.findall(r"([0-9.]+) \[([0-9.]+), ([0-9.]+)\]", line)]


def _full(summary, distribution, kind, metric):
    sel = summary[(summary.distribution == distribution) & (summary.kind == kind)
                  & (summary.metric == metric)]
    assert len(sel) == 1, "expected one %s/%s/%s row, got %d" % (
        distribution, kind, metric, len(sel))
    row = sel.iloc[0]
    # a cell printed under the declared aggregation must have been computed under it,
    # from prediction files, with the cluster bootstrap
    assert row["aggregation"] == "pooled", (distribution, kind, metric, row["aggregation"])
    assert str(row["ci_method"]).startswith("cluster_bootstrap"), (distribution, kind, metric)
    return row


def _scarce():
    flags = pd.read_csv(os.path.join(ROOT, "analysis", "leakage", "scarce_minority.csv"))
    return {(r.partition, r.kind) for r in flags[flags.flagged == 1].itertuples()}


def _expected_dagger(scarce, distribution, metric):
    """Pooled cells: the pooled unit's flag (centralized); client-mean cells: per client."""
    if metric == SECONDARY_BA:
        return (distribution, "fl") in scarce or (distribution, "local") in scarce
    return (distribution, "centralized") in scarce


def _cells_with_dagger(line):
    return [(tuple(float(x) for x in m[:3]), bool(m[3])) for m in
            re.findall(r"([0-9.]+) \[([0-9.]+), ([0-9.]+)\](\$\^\{\\dagger\}\$)?", line)]


def _check_ci(cell, row, what):
    for printed, value in zip(cell, (row["mean"], row["ci_low"], row["ci_high"])):
        assert printed == pytest.approx(round(float(value) * 100, 1), abs=0.051), (
            "%s: paper %s, analysis %.4f" % (what, cell, float(value) * 100))


@pytest.mark.parametrize("label,name", sorted(GENERATED.items()))
def test_paper_inputs_the_generated_tabular(label, name):
    tex = open(MAIN_TEX, encoding="utf-8").read()
    start = tex.index(r"\label{%s}" % label)
    end = tex.index(r"\end{table", start)
    block = tex[start:end]
    assert r"\input{tables/%s}" % name in block, "%s does not input %s" % (label, name)
    assert r"\begin{tabular}" not in block, "%s still holds a hand-typed tabular" % label
    assert os.path.isfile(os.path.join(TABLES, name))


REFERENCE_ROWS = [("centralized", "Centralized"), ("local", "Local-only")]


@pytest.mark.parametrize("distribution,block", [("iid", 1), ("non_iid_label", 2)])
@pytest.mark.parametrize("kind,method", REFERENCE_ROWS)
def test_fullmetrics_rows_match_summary(distribution, block, kind, method):
    summary = _summary()
    halves = _generated("fullmetrics_tabular.tex").split(r"\multirow")
    line = [l for l in halves[block].splitlines() if "& %s &" % method in l][0]
    cis = _ci_cells(line)
    assert len(cis) == 2, line
    _check_ci(cis[0], _full(summary, distribution, kind, PRIMARY_BA),
              "%s %s BA pooled" % (distribution, method))
    _check_ci(cis[1], _full(summary, distribution, kind, SECONDARY_BA),
              "%s %s BA client mean" % (distribution, method))
    scarce = _scarce()
    for (cell, dagger), metric in zip(_cells_with_dagger(line), (PRIMARY_BA, SECONDARY_BA)):
        assert dagger == _expected_dagger(scarce, distribution, metric), (distribution, method, metric)
    cells = _cells(line)
    assert len(cells) == len(FULLMETRICS_COLUMNS) - 1
    for (printed_mean, printed_std), (metric, scale) in zip(cells, FULLMETRICS_COLUMNS[1:]):
        mean, std = _lookup(summary, distribution, kind, metric)
        digits = 2 if scale == 1.0 else 1
        assert printed_mean == pytest.approx(round(mean * scale, digits), abs=0.05), (
            "%s %s %s: paper says %.2f, analysis says %.4f"
            % (distribution, method, metric, printed_mean, mean * scale))
        assert printed_std == pytest.approx(round(std * scale, digits), abs=0.05), (
            "%s %s %s std: paper says %.2f, analysis says %.4f"
            % (distribution, method, metric, printed_std, std * scale))


def test_fullmetrics_labels_are_where_the_cells_assume():
    text = _generated("fullmetrics_tabular.tex")
    header = [l for l in text.splitlines() if l.startswith(r"\textbf{Dist.}")][0]
    order = [r"\textbf{Bal.\ acc.}", r"\textbf{Bal.\ acc.,} \textbf{client mean}", r"\textbf{MCC}",
             r"\textbf{Acc.}", r"\textbf{Sens.}", r"\textbf{Spec.}", r"\textbf{Macro-}$F_1$",
             r"\textbf{ROC-AUC}"]
    positions = [header.index(h) for h in order]
    assert positions == sorted(positions), header
    blocks = text.split(r"\multirow")
    assert blocks[1].startswith("{5}{*}{IID}") and blocks[2].startswith("{5}{*}{Non-IID}")


def _two_block_rows(text, method):
    """The pooled-block and client-mean-block rows of one method, in order."""
    return [l for l in text.splitlines() if re.search(r"(^|& )%s &" % re.escape(method), l)]


@pytest.mark.parametrize("kind,method", REFERENCE_ROWS)
def test_dirichlet_reference_rows_match_summary(kind, method):
    summary = _summary()
    text = _generated("dirichlet_tabular.tex")
    header = [l for l in text.splitlines() if l.startswith(r"\textbf{Method}")][0]
    alphas = re.findall(r"alpha\{=\}([0-9.]+)", header)
    parts = {"0.1": "dirichlet_0.1", "0.5": "dirichlet_0.5", "1.0": "dirichlet_1"}
    cols = [parts[a] for a in alphas]
    assert sorted(cols) == sorted(parts.values())
    pooled, mean = _two_block_rows(text, method)
    scarce = _scarce()
    for line, metric in ((pooled, PRIMARY_BA), (mean, SECONDARY_BA)):
        cells = _cells_with_dagger(line)
        assert len(cells) == len(cols), line
        for (cell, dagger), dist in zip(cells, cols):
            _check_ci(cell, _full(summary, dist, kind, metric), "%s %s %s" % (dist, method, metric))
            assert dagger == _expected_dagger(scarce, dist, metric), (dist, method, metric)
    lines = text.splitlines()
    assert lines.index([l for l in lines if "(primary)" in l][0]) < lines.index(pooled)
    assert lines.index(pooled) < lines.index([l for l in lines if "(secondary)" in l][0]) \
        < lines.index(mean)


def test_dirichlet_columns_follow_the_measured_skew():
    skew = pd.read_csv(os.path.join(ROOT, "analysis", "partition_skew.csv"))
    skew = skew[skew.node == "ALL"].set_index("partition")["jsd"]
    header = [l for l in _generated("dirichlet_tabular.tex").splitlines()
              if l.startswith(r"\textbf{Method}")][0]
    order = ["dirichlet_%s" % ("1" if a == "1.0" else a)
             for a in re.findall(r"alpha\{=\}([0-9.]+)", header)]
    assert list(skew[order]) == sorted(skew[order])
    jsd_row = [l for l in _generated("dirichlet_tabular.tex").splitlines() if "measured skew (JSD)" in l][0]
    printed = [float(x) for x in re.findall(r"\{\\footnotesize ([0-9.]+)\}", jsd_row)]
    assert printed == [round(float(skew[p]), 3) for p in order]


@pytest.mark.parametrize("kind,method", REFERENCE_ROWS)
def test_lowdata_reference_rows_match_summary(kind, method):
    summary = _summary()
    rows = _two_block_rows(_generated("lowdata_tabular.tex"), method)
    assert len(rows) == 4             # pooled IID, pooled Non-IID, mean IID, mean Non-IID
    scarce = _scarce()
    for line, (dist, metric) in zip(rows, [("iid", PRIMARY_BA), ("non_iid_label", PRIMARY_BA),
                                           ("iid", SECONDARY_BA), ("non_iid_label", SECONDARY_BA)]):
        cols = [dist, dist + "_sub0.05", dist + "_sub0.01"]
        cells = _cells_with_dagger(line)
        assert len(cells) == 3, line
        for (cell, dagger), col in zip(cells, cols):
            _check_ci(cell, _full(summary, col, kind, metric), "%s %s %s" % (col, method, metric))
            assert dagger == _expected_dagger(scarce, col, metric), (col, method, metric)


def test_lowdata_labels_are_where_the_cells_assume():
    text = _generated("lowdata_tabular.tex")
    lines = text.splitlines()
    header = [l for l in lines if l.startswith(r"\textbf{Dist.}")][0]
    rhos = re.findall(r"rho\{=\}([0-9.]+)", header)
    assert rhos == ["1.00", "0.05", "0.01"]
    primary = [i for i, l in enumerate(lines) if "(primary)" in l]
    secondary = [i for i, l in enumerate(lines) if "(secondary)" in l]
    assert len(primary) == len(secondary) == 1 and primary[0] < secondary[0]
    labels = [re.search(r"\{\*\}\{([^}]+)\}", l).group(1) for l in lines if r"\multirow" in l]
    assert labels == ["IID", "Non-IID", "IID", "Non-IID"]


#: the final-epoch reference cells tab:dirichlet and tab:lowdata carried until
#: 2026-09-27 under a "selected round" caption; they must not come back
SUPERSEDED_CELLS = ("90.5 [81.0, 99.9]", "88.8 [72.4, 100]", "76.0 [71.1, 80.9]",
                    "58.7 [50.0, 67.4]", "80.1 [60.3, 100]", "87.7 [76.4, 99.0]",
                    "92.0 [89.5, 94.4]", "76.6 [71.6, 81.5]", "94.5 [92.4, 96.6]",
                    "87.9 [85.0, 90.8]", "89.7 [79.0, 100]", "81.0 [78.0, 84.0]",
                    "89.1 [82.7, 95.6]", "80.4 [79.1, 81.6]", "91.6 [80.7, 100]",
                    "85.3 [75.8, 94.8]", "90.8 [81.1, 100]", "79.8 [59.5, 100]")


def test_superseded_final_epoch_cells_are_gone():
    tex = open(MAIN_TEX, encoding="utf-8").read()
    for cell in SUPERSEDED_CELLS:
        assert cell not in tex, "superseded final-epoch cell %r is back in main.tex" % cell


def test_communication_volume_is_the_measured_one():
    """Three payloads per client per round: 165.5 MB for three rounds, not 110.3."""
    tex = open(MAIN_TEX, encoding="utf-8").read()
    runs = pd.read_csv(os.path.join(ROOT, "analysis", "runs.csv"))
    fl = runs[(runs.protocol == "group") & (runs.kind == "fl") & (runs.num_rounds == 3)]
    mb = sorted(set(round(float(v), 1) for v in fl.final_cumulative_mb.dropna()))
    assert mb == [165.5]
    assert "110.3" not in tex
    assert "$165.5$\\,MB" in tex
    assert r"B(R) \;=\; 3\,R\,K\,|w|" in tex


@pytest.mark.parametrize("distribution,kind,method", [
    ("iid", "centralized", "Centralized"),
    ("iid", "local", "Local-only"),
    ("non_iid_label", "centralized", "Centralized"),
    ("non_iid_label", "local", "Local-only"),
])
def test_protocol_effect_group_column_matches_summary(distribution, kind, method):
    """The group-level column of tab:protocol_effect is selected-round accuracy."""
    tex = open(MAIN_TEX, encoding="utf-8").read()
    summary = _summary()
    line = _row(tex, "tab:protocol_effect", method, distribution)
    cells = _cells(line)
    assert len(cells) == 2, "expected an image-level and a group-level cell"

    mean, std = _lookup(summary, distribution, kind, "selected_test_accuracy")
    printed_mean, printed_std = cells[1]
    assert printed_mean == pytest.approx(round(mean * 100, 1), abs=0.05), (
        "%s %s: paper says %.2f, analysis says %.4f"
        % (distribution, method, printed_mean, mean * 100))
    assert printed_std == pytest.approx(round(std * 100, 1), abs=0.05)


def test_paper_does_not_report_the_superseded_final_epoch_references():
    """78.3 % / 90.9 % may appear only where they are named as the old protocol.

    They were the headline references before the selection rule was declared.
    Any *unlabelled* occurrence is a cell that was missed when the tables were
    regenerated.
    """
    tex = open(MAIN_TEX, encoding="utf-8").read()
    for value in ("78.3", "90.9"):
        # a whole value, so that unrelated v1 numbers such as 78.36 do not match
        for match in re.finditer(re.escape(value) + r"(?!\d)", tex):
            window = tex[max(0, match.start() - 400):match.start() + 200]
            assert "final-epoch" in window or "final epoch" in window, (
                "%r appears at offset %d without being labelled as the superseded "
                "final-epoch protocol" % (value, match.start()))


def test_time_table_reports_both_aggregations_from_the_summary():
    """tab:time (\input by main.tex) prints balanced accuracy pooled and as the client
    mean, with the cluster-bootstrap interval, for the 3-round default-point runs."""
    text = open(os.path.join(TABLES, "time.tex"), encoding="utf-8").read()
    assert text.count(r"\begin{table*}") == 1
    summary = _summary()
    names = {"FedAvg": ("fedavg", None), r"FedProx($\mu$=0.01)": ("fedprox_0.01", 0.01)}
    checked = 0
    for line in text.splitlines():
        m = re.match(r"3N (IID|Label skew) (.+?) & ", line)
        if not m or m.group(2) not in names:
            continue
        dist = "iid" if m.group(1) == "IID" else "non_iid_label"
        strategy = names[m.group(2)][0]
        cis = _ci_cells(line)[1:]            # the first is the time interval
        assert len(cis) == 2, line
        for cell, metric in zip(cis, (PRIMARY_BA, SECONDARY_BA)):
            sel = summary[(summary.distribution == dist) & (summary.kind == "fl")
                          & (summary.strategy == strategy) & (summary.metric == metric)
                          & (summary.num_rounds == 3) & (summary.local_epochs == 5)
                          & (summary.lr == 0.001) & (summary.power_config == "heterogeneous")]
            assert len(sel) == 1
            _check_ci(cell, sel.iloc[0], "time %s %s %s" % (dist, strategy, metric))
            checked += 1
    assert checked == 8


def test_aggregation_flip_list_header_matches_its_csv():
    csv = os.path.join(ROOT, "analysis", "aggregation_flips.csv")
    md = open(os.path.join(ROOT, "analysis", "aggregation_flips.md"), encoding="utf-8").read()
    df = pd.read_csv(csv)
    for subset in ("full", "clean"):
        sub = df[df.subset == subset]
        line = [l for l in md.splitlines() if l.startswith("- %s set:" % subset)][0]
        numbers = [int(x) for x in re.findall(r"(\d+)", line)]
        assert numbers[:4] == [len(sub), int(sub.verdict_flip.sum()),
                               int((sub.direction_flip & ~sub.verdict_flip).sum()),
                               int((~sub.stable).sum())], line
    # every pair appears once: reference-vs-reference pairs are not duplicated per power group
    keys = df[["subset", "distribution", "a", "b"]].astype(str).agg("|".join, axis=1)
    assert keys.is_unique


def test_fedbn_bn_share_is_the_computed_one():
    """FedBN transmits the full model; the BN share of a transfer comes from
    scripts/fedbn_payload.py (analysis/fedbn_payload.json), not from the keyboard."""
    import json

    tex = open(MAIN_TEX, encoding="utf-8").read()
    path = os.path.join(ROOT, "analysis", "fedbn_payload.json")
    share = json.load(open(path, encoding="utf-8"))["bn_share_of_bytes"]
    assert "never transmitted" not in tex
    assert "$%.2f$\%% of one model transfer" % (100 * share) in tex
    try:
        import torch  # noqa: F401
    except ImportError:
        return
    import sys
    sys.path.insert(0, ROOT)
    from scripts.fedbn_payload import bn_payload_share
    assert bn_payload_share()["bn_share_of_bytes"] == pytest.approx(share, rel=0, abs=1e-12)
