#!/usr/bin/env python3
"""FedRGBD -- tab:loso from the analysis of question (a) (never typed by hand, CLAUDE.md rule 4).

Reads ``scripts/camera_analysis_a.py``'s output (``pairs.csv``, ``ba_matrix.csv``,
``hierarchy_contrast.csv``) and writes the tabular environment of ``tab:loso``: the six
ordered pairs of family A-RGB (primary) in the paper's row order, then the contrast K.

  BA(X on X), BA(X on Y): pooled leave-one-scene-out balanced accuracy, mean over seeds,
                          with the scene-bootstrap 95 % interval, in %
  D(X -> Y)             : percentage points, with its interval
  Holm p                : Holm-adjusted bootstrap p of family A-RGB (m = 6); K: its single p
  Verdict               : the Holm verdict (the headline, prereg sec. 4), verbatim; K: the
                          interval verdict, verbatim

    python scripts/camera_export_loso_table.py --analysis_dir analysis/camera/a \\
        --output paper/tables/loso_tabular.tex
"""

from __future__ import annotations

import argparse
import os
import sys
from typing import Optional, Sequence

import pandas as pd

REPO = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
#: the row order of tab:loso in paper/main.tex
ROWS = (("node_a", "node_b"), ("node_a", "node_c"), ("node_b", "node_a"),
        ("node_b", "node_c"), ("node_c", "node_a"), ("node_c", "node_b"))
TEX_SENSOR = {"node_a": "D435if", "node_b": "D435i", "node_c": "ZED 2i"}
GENERATED = "% generated by scripts/camera_export_loso_table.py -- do not edit by hand"
SYNTHETIC = "% SYNTHETIC dry run -- random frames; these numbers are meaningless"


def _ci(v, lo, hi, scale=100.0, signed=False) -> str:
    fmt = "%+.1f" if signed else "%.1f"
    return (fmt + " [%.1f, %.1f]") % (scale * v, scale * lo, scale * hi)


def tabular(analysis_dir: str, synthetic: bool = False) -> str:
    pairs = pd.read_csv(os.path.join(analysis_dir, "pairs.csv"))
    matrix = pd.read_csv(os.path.join(analysis_dir, "ba_matrix.csv"))
    contrast = pd.read_csv(os.path.join(analysis_dir, "hierarchy_contrast.csv"))
    pairs = pairs[pairs["family"] == "A-RGB"]
    matrix = matrix[(matrix["protocol"] == "loso") & (matrix["modality"] == "rgb")]
    contrast = contrast[contrast["modality"] == "rgb"]
    if len(pairs) != 6 or len(contrast) != 1:
        raise SystemExit("family A-RGB needs 6 pairs and one contrast K, found %d and %d"
                         % (len(pairs), len(contrast)))

    def ba(x, y):
        r = matrix[(matrix["source"] == x) & (matrix["target"] == y)]
        if len(r) != 1:
            raise SystemExit("ba_matrix.csv has %d rows for %s -> %s" % (len(r), x, y))
        r = r.iloc[0]
        return _ci(r["balanced_accuracy"], r["ci_low"], r["ci_high"])

    out = [GENERATED] + ([SYNTHETIC] if synthetic else []) + [
        r"\begin{tabular}{@{}lccccl@{}}", r"\toprule",
        r"\textbf{Pair $X \rightarrow Y$} & \textbf{BA($X$ on $X$)} & \textbf{BA($X$ on $Y$)} "
        r"& \textbf{$D(X\rightarrow Y)$} & \textbf{Holm $p$} & \textbf{Verdict} \\",
        r"\midrule"]
    for x, y in ROWS:
        r = pairs[(pairs["source"] == x) & (pairs["target"] == y)]
        if len(r) != 1:
            raise SystemExit("pairs.csv has %d A-RGB rows for %s -> %s" % (len(r), x, y))
        r = r.iloc[0]
        out.append(r"%s $\rightarrow$ %s & %s & %s & %s & %.3f & %s \\"
                   % (TEX_SENSOR[x], TEX_SENSOR[y], ba(x, x), ba(x, y),
                      _ci(r["diff"], r["ci_low"], r["ci_high"], signed=True), r["p_holm"],
                      r["verdict_holm"]))
    k = contrast.iloc[0]
    out += [r"\midrule",
            r"Contrast $K$ (hierarchy) & -- & -- & %s & %.3f\,(single test) & %s \\"
            % (_ci(k["K"], k["ci_low"], k["ci_high"], signed=True), k["p_boot"], k["verdict"]),
            r"\bottomrule", r"\end{tabular}"]
    return "\n".join(out) + "\n"


def main(argv: Optional[Sequence[str]] = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--analysis_dir", default=os.path.join("analysis", "camera", "a"))
    ap.add_argument("--output", default=os.path.join("paper", "tables", "loso_tabular.tex"))
    ap.add_argument("--synthetic", action="store_true",
                    help="mark the file as a synthetic dry run (never under paper/)")
    args = ap.parse_args(argv)
    out = os.path.abspath(args.output)
    if args.synthetic and os.path.commonpath([out, os.path.join(REPO, "paper")]) == \
            os.path.join(REPO, "paper"):
        raise SystemExit("a synthetic table is never written under paper/")
    text = tabular(args.analysis_dir, args.synthetic)
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print("wrote %s" % out)
    return 0


if __name__ == "__main__":
    sys.exit(main())
